//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goChord.goChordDb.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoChordContext : DbContext
    {
        public GoChordContext()
            : base("name=GoChordContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriesBySong> CategoriesBySong { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Song> Song { get; set; }
        public virtual DbSet<Songbook> Songbook { get; set; }
        public virtual DbSet<SongbookByUser> SongbookByUser { get; set; }
        public virtual DbSet<SongBySongbook> SongBySongbook { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
