//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goChord.goChordDb.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongbookByUser
    {
        public int songbooksByUserId { get; set; }
        public int userId { get; set; }
        public int songbookId { get; set; }
    
        public virtual Songbook Songbook { get; set; }
        public virtual User User { get; set; }
    }
}
